baseURL = 'https://maeken2010.github.io/'
languageCode = 'ja'
title = "Maeken's blog"
theme = "PaperMod"

[params]
  [params.homeInfoParams]
  Title = "Hi there 🍺"
  Content = "Welcome to my blog"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/maeken2010"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/maeken2010"
